# Generated by Django 5.2.6 on 2025-09-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='status',
            field=models.IntegerField(choices=[(0, 'Wolne'), (1, 'Zajęte')], default=0),
        ),
    ]
