# Generated by Django 5.2.6 on 2025-09-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='status',
            field=models.CharField(choices=[('FREE', 'Wolne'), ('OCCUPIED', 'Zajęte')], default='FREE', max_length=10),
        ),
    ]
