# Generated by Django 5.2.6 on 2025-09-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_parking', '0002_alter_parking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='status',
            field=models.CharField(choices=[('FREE', 'FREE'), ('OCCUPIED', 'OCCUPIED')], default='FREE', max_length=10),
        ),
    ]
