# Generated by Django 5.2.6 on 2025-09-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_parking', '0002_alter_parking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='status',
            field=models.IntegerField(choices=[(0, 'FREE'), (1, 'OCCUPIED')], default=0),
        ),
    ]
