# Generated by Django 5.2.5 on 2025-09-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_parking', '0003_alter_parking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='spot',
            field=models.CharField(max_length=4),
        ),
    ]
