# Generated by Django 5.2.6 on 2025-09-16 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_parking', '0003_alter_parking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('parking_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_parking.parking')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_parking.employee')),
            ],
        ),
    ]
