# Generated by Django 5.2.5 on 2025-09-17 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_parking', '0004_alter_reservation_spot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_parking.parking'),
        ),
    ]
